apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-deployment
  labels:
    app: verification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verification
  template:
    metadata:
      labels:
        app: verification
    spec:
      serviceAccountName: script-k8s-client
      containers:
        - name: verification
          image: verification-image
          imagePullPolicy: Never # needed for local images
          volumeMounts:
            - name: verification-volume-ro
              mountPath: /verification/
            - mountPath: "/work/data/"
              name: pv-storage
          command:
            - /bin/sh
            - -ec
            - |
              while true; do
                echo "Running verification script"
                bash /verification/verification-shell-script.sh
                sleep 3000
              done
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: pv-claim
        - name: verification-volume-ro
          configMap:
            name: verification-script
